name: Build and push to ecr
on: 
    workflow_dispatch:
        inputs:
            image-tag:
                description: 'tag for docker image' 
                required: true
            skip-dependency-check:
                description: 'This will skip npm audit step'
                required: false
                type: boolean
                default: false
            skip-test-cases:
                description: 'This will skip npm test step'
                required: false
                type: boolean
                default: false

permissions:
    id-token: write
    contents: read

jobs:
    audit-dependencies:
       uses: iansstuff15/startbootstrap-resume/.github/workflows/audit-dependency.yaml@master
       with:
           skip-dependency-check: ${{ inputs.skip-dependency-check }}

    run-test-cases: 
       needs: audit-dependencies
       uses: iansstuff15/startbootstrap-resume/.github/workflows/run-test-cases.yaml@master
       with: 
           skip-test-cases: ${{ !inputs.skip-test-cases }}
           

    create-docker-image:
        needs: run-test-cases
        runs-on: actions-runner-1

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Configure AWS
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  aws-region: us-east-1
                  role-to-assume: ${{secrets.GITHUBACTIONSOIDC}}

            - name: Cache Modules
              id: cache-node-modules
              uses: actions/cache/restore@v4
              with:
                  path: ./node_modules
                  key: node_modules
            
            - name: Install node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.11.0
                  cache: 'npm'

            - name: Build node project
              run: npm run build

            - name: Configure AWS
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  aws-region: us-east-1
                  role-to-assume: ${{secrets.GITHUBACTIONSOIDC}}
                  
            - name: ECR Login
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
              with:
                  provenance: false

            - name: Build and push image
              uses: docker/build-push-action@v6.10.0
              with:
                  context: .
                  push: true
                  tags: ${{ steps.login-ecr.outputs.registry }}/caimbridge-demo:${{ inputs.image-tag }}
                  provenance: true
                  sbom: true
              env:
                 DOCKER_BUILD_SUMMARY: true

            - name: Save cache
              if: always()
              uses: actions/cache/save@v4
              with:
                  path: ./dist
                  key: build_dist
              
                
