name: On Pull Request

on:
  pull_request:
       branches:
         - 'master'

jobs:
  audit:
    runs-on: actions-runner-1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: install node
        id: install-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
          
      - run: npm install
      - run: npm audit fix --force
      
